network:
  host: "0.0.0.0" #The IP for the host, the default value is 0.0.0.0
  port: "80" #The port where you want to deploy the server

apiRequest:
  token: "MY_SECRET_TOKEN" #the token of the api will be call to retrieve the data of the stations
  host: "172.16.8.241"
  port: "5000"

passwordRequest:
  token: "MY_SECRET_TOKEN" #the token of the api will be call for the password manager
  host: "172.16.8.241"
  port: "6969"

map:
  style: "mapbox://styles/02loveslollipop/clhalt9sp020b01p8a60a7bt0/draft" #The style of the map, it can either be one of the available in the documentation of plotly.express.density_mapbox or the link of an mapbox style.
  token: "pk.eyJ1IjoiMDJsb3Zlc2xvbGxpcG9wIiwiYSI6ImNsaGFscTFwdTBpYnUzaXBiamhqOXF1ZWIifQ.hPt8d7_7Vc5sAiBzMHRHSw" #required if using a custom map of mapBox or when the map style requiere it, for further information check: https://plotly.com/python-api-reference/generated/plotly.express.density_mapbox.html

web:
  debug: true #if you want to use Flask debug mode
  secretKey: "MY_EXTREMELY_HYPER_SECRET_TOKEN"



