version: '3.8'
services:
  siata-web:
    image: openmetasiata/web:1.0.0beta
    hostname: openmetasiata-web
    container_name: openmetasiata-web
    depends_on:
      - siata-db
      - siata-api
    networks:
      - default
    expose:
      - "80"
    ports:
      - "80:80"
  siata-db:
    image: openmetasiata/db:1.0.0beta
    hostname: openmetasiata-db
    container_name: openmetasiata-db
    expose:
      - "6969"
    networks:
      - default
  siata-api:
    image: openmetasiata/api:1.0.0beta
    hostname: openmetasiata-api
    container_name: openmetasiata-api
    expose:
      - "5000"
networks:
  default:
    ipam:
      config:
        - subnet: "192.168.1.0/24"